# This file was generated by GoReleaser. DO NOT EDIT.
cask "capydb" do
  version "1.5.0"

  on_macos do
    on_arm do
      sha256 "6fd8c5e04c4ef0c99708fcc8dc5bcda98ab05c0a0cd3cb606e9d3e8940971139"
      url "https://github.com/capydatabase/capydb-cli/releases/download/v#{version}/capydb_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "ea8e0036afd5ebb61afd5e08816326686aa228b00f5743a47f0e809df4d3360d"
      url "https://github.com/capydatabase/capydb-cli/releases/download/v#{version}/capydb_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1d65394346e8165d30b7d66ca192dd3096009d77dfa9383c9dd80cb4b306a9ce"
      url "https://github.com/capydatabase/capydb-cli/releases/download/v#{version}/capydb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e97f0777f6921bc2daa09079edbb24339097b2bd50f5355ce65e57803c68c245"
      url "https://github.com/capydatabase/capydb-cli/releases/download/v#{version}/capydb_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "capydb"
  desc "CapyDB CLI - simple Postgres hosting"
  homepage "https://capydb.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capydb"
  bash_completion "completions/capydb.bash"
  fish_completion "completions/capydb.fish"
  zsh_completion "completions/capydb.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capydb"]
    end
  end

  # No zap stanza required
end
