# This file was generated by GoReleaser. DO NOT EDIT.
cask "capydb" do
  version "1.5.0"

  on_macos do
    on_arm do
      sha256 "36dbf4bbfe2fdac8a63166902de059227f0b2479caa24ea5ff0abc8c1695e13f"
      url "https://github.com/capydatabase/capydb-cli/releases/download/v#{version}/capydb_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "c797e26512f53999b6fb1d7454bf05d8d1be04732589de17c4d7306387e6eb93"
      url "https://github.com/capydatabase/capydb-cli/releases/download/v#{version}/capydb_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8bccc3d074ebd60f2105be089120aed4348c53727cc398ed36778f272824b759"
      url "https://github.com/capydatabase/capydb-cli/releases/download/v#{version}/capydb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "197d8e283fa5e7e8f368d167c4d057474c158d987ef1ee4f185497f6e1be8ad2"
      url "https://github.com/capydatabase/capydb-cli/releases/download/v#{version}/capydb_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "capydb"
  desc "CapyDB CLI - simple Postgres hosting"
  homepage "https://capydb.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capydb"
  bash_completion "completions/capydb.bash"
  fish_completion "completions/capydb.fish"
  zsh_completion "completions/capydb.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capydb"]
    end
  end

  # No zap stanza required
end
