# This file was generated by GoReleaser. DO NOT EDIT.
cask "capydb" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "633a76ab4ee443cf5d68a510094fd4fde06470f05c30212762364e3f4513ccfd"
      url "https://github.com/capy-base/capydb-cli/releases/download/v#{version}/capydb_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "47720e4ec9cf7f35e970ea3f7150ea0e5d9cb381255d5298a1b69318113ae420"
      url "https://github.com/capy-base/capydb-cli/releases/download/v#{version}/capydb_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "239eee33b296bb2bdab25735350aefba01285fd889f1e25e429200883c54b683"
      url "https://github.com/capy-base/capydb-cli/releases/download/v#{version}/capydb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e98ee4ef6faf749ac4812f32adc1ddd8b266045f3e34b525a6a58e30ca177dc"
      url "https://github.com/capy-base/capydb-cli/releases/download/v#{version}/capydb_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "capydb"
  desc "CapyDB CLI - simple Postgres hosting"
  homepage "https://capydb.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capydb"
  bash_completion "completions/capydb.bash"
  fish_completion "completions/capydb.fish"
  zsh_completion "completions/capydb.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capydb"]
    end
  end

  # No zap stanza required
end
